<script>
 import PSpace from '../layout/PSpace.svelte'
 import DefLink from '../text/DefLink.svelte'
</script>

<section class="section white-bg">
 <div class="container">
	 <h1 class="title">Overview</h1>
		<h2 class="subtitle">Saltpack encryption for SPAs.</h2>

	 <p>
		 <DefLink url={"https://saltpack.org/"} text={"Saltpack"} /> is an encryption format pioneered by <DefLink url={"https://keybase.io/"} text={"Keybase"} />.<br />
		 Saltpack composes the <DefLink url={"https://nacl.cr.yp.to/"} text={"NaCL"} /> and <DefLink url={"https://msgpack.org/index.html"} text={"MessagePack"} /> <strong>primitives</strong> into a sound cryptographic <strong>system</strong>.
		</p>

  <PSpace />

  <p>
   Messages of any length can be encrypted for many recipients based on their <strong>public key</strong>.<br />
   Recipients cannot see other public keys so messages preserve <strong>pseudonimity</strong>.<br />
   New messages <strong>reveal nothing</strong> about existing or future messages.<br />
   The sender can <strong>add new recipients</strong> after the initial encryption process.
  </p>

  <PSpace />

  <p>
   Embedding encrypted saltpack messages in public content allows users with matching keypairs to securely receive private content.<br />
   The public content can be generated by any static site generator such as <DefLink url={"https://www.gatsbyjs.com/"} text={"Gatsby"} /> or <DefLink url={"https://jekyllrb.com/"} text={"Jekyll"} />.<br />
   Senders and recipients will need to manage their own keypairs where the content is created and read.
  </p>

 </div>
</section>
